# NUMPY

* Numpy is numerical python
* Numpy is python library
* Numpy is scientific operation 
* Numpy is nd array
* Numpy is 50x faster than noramal array

In [25]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [26]:
import math

In [27]:
math. sqrt(4)

2.0

In [28]:
l = [1,2,3,4,"hello"]
import numpy 
numpy.array([l])

array([['1', '2', '3', '4', 'hello']], dtype='<U21')

In [29]:
import numpy as np

#Numpy -> its a multidimensional array library .i,e u can store

In [30]:
#Numpy -> its a multidimensional array librabry .i,e u can store all sort of data.like 1-d,2-d,n-d;
#downloading Numpy(remeber to pip or pip3 install numpy first on terminal)

In [31]:
import numpy as np


#THE BASICS :

#initialize array

In [32]:
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

one dimensional array : [1 2 3]


In [34]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array:",b)

two dimensional array: [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [35]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)


dimension of a : 1
dimension of b : 2


In [ ]:
#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)


shape of a : (3,)
shape of b : (2, 4)


In [ ]:
#Get  Type
print("a type is :",a.dtype)

#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;


a type is : int16
size of a : 3


In [ ]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)


a item size : 2
total size is a: 6


#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC


In [ ]:
#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]

#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);

#Get specific column[:,column]
print("column :",b[:,1])


row : [2.1]
column : [2. 3.]


In [ ]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])


subset of specific row [3.  4.5]


In [ ]:
#change element
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

In [ ]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)


two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [ ]:
# initialize array
a=np.array 

# 3-d Example

In [ ]:
c=np.array([[
            [1,2,4],[3,4,5]
          ],
          [
         [5,6,6],[7,8,7]
     ]
     ]) 

In [ ]:
c

array([[[1, 2, 4],
        [3, 4, 5]],

       [[5, 6, 6],
        [7, 8, 7]]])

In [ ]:
type(c)

numpy.ndarray

In [ ]:
c.ndim

3

In [ ]:
c.shape

(2, 2, 3)

In [ ]:
c.size

12

## calculate the  memory space took for c numpy array

In [ ]:
c.dtype

dtype('int64')

In [ ]:
c.itemsize *c.size 

96

In [ ]:
# get specific element (work outside in)
print ("specified element is :",c[1,1,2])

specified element is : 7


In [ ]:
c[1,1,2] = 100
c

array([[[  1,   2,   4],
        [  3,   4,   5]],

       [[  5,   6,   6],
        [  7,   8, 100]]])

initializing diff types of array

In [36]:
zm=np.zeros((3,4))

In [ ]:
zm

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

all 1's matrix

In [37]:

np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
ones=np.ones((4,3))

In [39]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
ones[1,1] =100
ones

array([[  1.,   1.,   1.],
       [  1., 100.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [41]:
m100=np.full((4,5),100,dtype="float")

In [42]:
m100

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [43]:
np.full_like(m100,200,dtype="float")

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

In [44]:
np.random.random_sample((2,3))

array([[0.58966525, 0.67000171, 0.3696156 ],
       [0.77269461, 0.60054353, 0.88868073]])

In [45]:
np.random.rand(2,3)

array([[0.00990902, 0.39036868, 0.21136883],
       [0.33076882, 0.09789199, 0.10164174]])

In [46]:
np.random.randint(6,9,size=(3,3))

array([[8, 7, 6],
       [8, 8, 7],
       [7, 8, 7]], dtype=int32)